logo = "images/logo.png"
footerLogo  = "images/logo-m.png"
# Meta data
description = "Your local event freelancers"
author = "Sommos"
# Google Analitycs
google_analitycs_id = "G-81H578T2QX"
# post share
post_share = true

# preloader
[preloader]
enable = true
preloader = "images/logo.png"

# css plugins
[[plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[plugins.css]]
link = "plugins/slick/slick.css"
[[plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[plugins.js]]
link = "plugins/slick/slick.min.js"
[[plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[plugins.js]]
link = "plugins/google-map/map.js"

# social
[[social]]
icon = "ti-facebook"
link = "https://www.facebook.com/sommos.work/"

[[social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/sommoswork/about/"

[[social]]
icon = "ti-instagram"
link = "https://www.instagram.com/Sommos.work/"